version: "3"

services:
  pictochatdb-db:
    restart: always
    image: postgres:11.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=me
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pictochatdb        
    # volumes:
    #   - ./docker-volumes/pictochatdb/data:/var/lib/postgresql/data
